Item.DROP_DETAIL_TYPE_SETTING = nil;

Item.DROP_DETAIL_TYPE={1,2,3,4,5,6,7,8,9,10,11,12};

Item.DROP_ITEM_MELEE_DETAIL_TYPE = 1;
Item.DROP_ITEM_RANGE_DETAIL_TYPE = 2;
Item.DROP_ITEM_ARMOR_DETAIL_TYPE = 3;
Item.DROP_ITEM_RING_DETAIL_TYPE = 4;
Item.DROP_ITEM_NECKLACE_DETAIL_TYPE = 5;
Item.DROP_ITEM_AMULET_DETAIL_TYPE = 6;
Item.DROP_ITEM_BOOTS_DETAIL_TYPE = 7;
Item.DROP_ITEM_BELT_DETAIL_TYPE = 8;
Item.DROP_ITEM_HELM_DETAIL_TYPE = 9;
Item.DROP_ITEM_CUFF_DETAIL_TYPE = 10;

Item.DROP_ITEM_MELEE_PARTICULAR_TYPE = {1,2,3,4,5,6};
Item.DROP_ITEM_RANGE_PARTICULAR_TYPE = {1,2,3};
Item.DROP_ITEM_ARMOR_PARTICULAR_TYPE = {2,3,4,6,7,8};
Item.DROP_ITEM_RING_PARTICULAR_TYPE = {1};
Item.DROP_ITEM_NECKLACE_PARTICULAR_TYPE = {1};
Item.DROP_ITEM_AMULET_PARTICULAR_TYPE = {1};
Item.DROP_ITEM_BOOTS_PARTICULAR_TYPE = {1,2};
Item.DROP_ITEM_BELT_PARTICULAR_TYPE = {1,2};
Item.DROP_ITEM_HELM_PARTICULAR_TYPE = {2,3,4,6,7,8};
Item.DROP_ITEM_CUFF_PARTICULAR_TYPE = {1,2};

Item.DROP_RATE_PERCENT = 1;